name: mfa_demo
description: MFA Demo.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  # dev
  circular_countdown_timer: 
    path: D:/github_repo/circular_countdown_timer/
  
  # deploy
  # circular_countdown_timer: 
  #   git:
  #     url: https://github.com/guchengxi1994/circular_countdown_timer
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_smart_dialog: ^4.9.0+1
  provider: ^6.0.3
  window_size:
    git:
      url: https://gitee.com/guchengxi1994/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatar/a.jpg
